cert:
  private_key_path: cert/private.pem
  public_key_path: cert/public.pem

server:
  host: 0.0.0.0
  http_port: 8080
  grpc_port: 8081

redis:
  host: 127.0.0.1
  port: 6379
  pwd: secret
  database: 0

db:
  mongo:
    dsn: mongodb://127.0.0.1:27017
    database: test

caching:
  enable: true
  ttl: 5m

service:
  session:
    access_token_ttl: 15d
    refresh_token_ttl: 30d
