server:
  host: 0.0.0.0
  http_port: 8080
  grpc_port: 8081

redis:
  host: 127.0.0.1
  port: 6379
  pwd: secret
  database: 0

db:
  mongo:
    dsn: mongodb://localhost:27017/
    database: auth-db

caching:
  enable: true
  ttl: 5m

service:
  session:
    access_token_ttl: 15d
    refresh_token_ttl: 30d
  enable_encryption: true

auth:
  aud: "auth-svc"
  external_envoy:
    header: "authorization"
    scheme: "bearer"

  client:
    type: "rsa" # "rsa" or "hmac"
    rsa256:
      private_key_path: cert/private.pem
      public_key_path: cert/public.pem
    hmac:
      secret: "secret"

  m2m:
    enable_assertion: true
    type: "rsa" # "rsa" or "hmac"
    whitelist:
      internal_services:
        - name: "customer-svc"
          public_key: "public_key"
        - name: "admin-svc"
          public_key: "public_key"
